##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.6.0.1-B1] date: [Sun Jul 06 12:28:31 PDT 2025] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = stm32f042_tinyusb


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/syscalls.c \
Core/Src/stm32f0xx_it.c \
Core/Src/stm32f0xx_hal_msp.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_ll_usb.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_uart.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_uart_ex.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_rcc.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_rcc_ex.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_i2c.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_i2c_ex.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_gpio.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_dma.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_cortex.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_pwr.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_pwr_ex.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_flash.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_flash_ex.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_exti.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_pcd.c \
Drivers/stm32f0xx-hal-driver/Src/stm32f0xx_hal_pcd_ex.c \
Core/Src/system_stm32f0xx.c \
Drivers/tinyusb/src/class/vendor/vendor_device.c \
Drivers/tinyusb/src/class/hid/hid_device.c \
Drivers/tinyusb/src/class/hid/hid_host.c \
Drivers/tinyusb/src/common/tusb_fifo.c \
Drivers/tinyusb/src/tusb.c \
Drivers/tinyusb/src/device/usbd.c \
Drivers/tinyusb/src/device/usbd_control.c \
Drivers/tinyusb/src/portable/st/stm32_fsdev/dcd_stm32_fsdev.c \
Core/Src/usb_descriptors.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f042x6.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m0

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F042x6 \
-DCFG_TUSB_MCU=OPT_MCU_STM32F0


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/stm32f0xx-hal-driver/Inc \
-IDrivers/stm32f0xx-hal-driver/Inc/Legacy \
-IDrivers/cmsis-device-f0/Include \
-IDrivers/cmsis-core/Include \
-IDrivers/tinyusb/src


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F042XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	

$(BUILD_DIR):
	mkdir $@		

### added by tod
#
###

# device must be in DFU mode (BOOT0 pin pulled HIGH)
dfu:
	dfu-util -a 0 -s 0x08000000:leave -D ./build/$(TARGET).bin

# flash via STlink SWD (maybe built-in to Nucleo/Discovery board)
flash:
	openocd -f interface/stlink.cfg -f target/stm32f0x.cfg -c "program ./build/$(TARGET).bin  reset exit 0x8000000"


#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
